language: node_js
cache:
  directories:
    - node_modules
    - "$PANDOC"
notifications:
  email: false
node_js: 8
before_install:
  - mkdir -p "$PANDOC"
  - if [[ ! -f "$PANDOC/pandoc.deb" ]]; then curl -L "$PANDOC_DEB" > "$PANDOC/pandoc.deb" && dpkg -x "$PANDOC/pandoc.deb" "$PANDOC"; fi
  - export PATH="$PANDOC/usr/bin:$PATH"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
env:
  global:
    - PANDOC="$HOME/.pandoc"
    - PANDOC_DEB="https://github.com/jgm/pandoc/releases/download/2.1.3/pandoc-2.1.3-1-amd64.deb"
